// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: batch.go

package gensqlc

import (
	"context"
	"errors"

	"github.com/jackc/pgx/v5"
)

var (
	ErrBatchAlreadyClosed = errors.New("batch already closed")
)

const userDeleteByEmailBatchAll = `-- name: UserDeleteByEmailBatchAll :batchexec
delete from "user" where  email = $1
`

type UserDeleteByEmailBatchAllBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

func (q *Queries) UserDeleteByEmailBatchAll(ctx context.Context, email []string) *UserDeleteByEmailBatchAllBatchResults {
	batch := &pgx.Batch{}
	for _, a := range email {
		vals := []interface{}{
			a,
		}
		batch.Queue(userDeleteByEmailBatchAll, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &UserDeleteByEmailBatchAllBatchResults{br, len(email), false}
}

func (b *UserDeleteByEmailBatchAllBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *UserDeleteByEmailBatchAllBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}

const userSelectByEmailBatchMany = `-- name: UserSelectByEmailBatchMany :batchexec
select id, email, password, first_name, last_name, created_at, updated_at, deleted_at from "user" where email = $1
`

type UserSelectByEmailBatchManyBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

func (q *Queries) UserSelectByEmailBatchMany(ctx context.Context, email []string) *UserSelectByEmailBatchManyBatchResults {
	batch := &pgx.Batch{}
	for _, a := range email {
		vals := []interface{}{
			a,
		}
		batch.Queue(userSelectByEmailBatchMany, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &UserSelectByEmailBatchManyBatchResults{br, len(email), false}
}

func (b *UserSelectByEmailBatchManyBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *UserSelectByEmailBatchManyBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}

const userSelectByEmailBatchOne = `-- name: UserSelectByEmailBatchOne :batchone
select id, email, password, first_name, last_name, created_at, updated_at, deleted_at from "user" where email = $1
`

type UserSelectByEmailBatchOneBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

func (q *Queries) UserSelectByEmailBatchOne(ctx context.Context, email []string) *UserSelectByEmailBatchOneBatchResults {
	batch := &pgx.Batch{}
	for _, a := range email {
		vals := []interface{}{
			a,
		}
		batch.Queue(userSelectByEmailBatchOne, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &UserSelectByEmailBatchOneBatchResults{br, len(email), false}
}

func (b *UserSelectByEmailBatchOneBatchResults) QueryRow(f func(int, User, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		var i User
		if b.closed {
			if f != nil {
				f(t, i, ErrBatchAlreadyClosed)
			}
			continue
		}
		row := b.br.QueryRow()
		err := row.Scan(
			&i.Id,
			&i.Email,
			&i.Password,
			&i.FirstName,
			&i.LastName,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		)
		if f != nil {
			f(t, i, err)
		}
	}
}

func (b *UserSelectByEmailBatchOneBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}
