// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: copyfrom.go

package gensqlc

import (
	"context"
)

// iteratorForUserInsertManyCopyFrom implements pgx.CopyFromSource.
type iteratorForUserInsertManyCopyFrom struct {
	rows                 []UserInsertManyCopyFromParams
	skippedFirstNextCall bool
}

func (r *iteratorForUserInsertManyCopyFrom) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForUserInsertManyCopyFrom) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].Email,
		r.rows[0].Password,
		r.rows[0].FirstName,
		r.rows[0].LastName,
	}, nil
}

func (r iteratorForUserInsertManyCopyFrom) Err() error {
	return nil
}

func (q *Queries) UserInsertManyCopyFrom(ctx context.Context, arg []UserInsertManyCopyFromParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"user"}, []string{"email", "password", "first_name", "last_name"}, &iteratorForUserInsertManyCopyFrom{rows: arg})
}
