// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package gensqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	Id        int64
	Email     string
	Password  []byte
	FirstName string
	LastName  string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	DeletedAt pgtype.Timestamptz
}
