// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package gensqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgconn"
)

type Querier interface {
	UserDeleteByEmailBatchAll(ctx context.Context, email []string) *UserDeleteByEmailBatchAllBatchResults
	UserDeleteById(ctx context.Context, id int64) error
	UserGetByEmail(ctx context.Context, email string) (User, error)
	UserGetById(ctx context.Context, id int64) (User, error)
	UserHardDeleteAll(ctx context.Context) (pgconn.CommandTag, error)
	UserHardDeleteAllCnt(ctx context.Context) (int64, error)
	UserHardDeleteByEmail(ctx context.Context, email string) error
	UserInsert(ctx context.Context, arg UserInsertParams) (User, error)
	UserInsertManyCopyFrom(ctx context.Context, arg []UserInsertManyCopyFromParams) (int64, error)
	UserList(ctx context.Context) ([]User, error)
	UserSelectByEmailBatchMany(ctx context.Context, email []string) *UserSelectByEmailBatchManyBatchResults
	UserSelectByEmailBatchOne(ctx context.Context, email []string) *UserSelectByEmailBatchOneBatchResults
}

var _ Querier = (*Queries)(nil)
