// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: queries.sql

package gensqlc

import (
	"context"
	"fmt"
)

const userCreate = `-- name: UserCreate :one
insert into "user" (
    email
  , password
  , first_name
  , last_name
) values (
    $1
  , $2
  , $3
  , $4
)
returning id, email, password, first_name, last_name, created_at, updated_at, deleted_at
`

type UserCreateParams struct {
	Email     string
	Password  []byte
	FirstName string
	LastName  string
}

func (q *Queries) UserCreate(ctx context.Context, arg UserCreateParams) (User, error) {
	row := q.db.QueryRow(ctx, userCreate,
		arg.Email,
		arg.Password,
		arg.FirstName,
		arg.LastName,
	)
	var i User
	err := row.Scan(
		&i.Id,
		&i.Email,
		&i.Password,
		&i.FirstName,
		&i.LastName,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	if err != nil {
		err = fmt.Errorf("query UserCreate: %w", err)
	}
	return i, err
}

const userDeleteById = `-- name: UserDeleteById :exec
update "user"
  set deleted_at = now()
where id = $1
`

func (q *Queries) UserDeleteById(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, userDeleteById, id)
	if err != nil {
		return fmt.Errorf("query UserDeleteById: %w", err)
	}
	return nil
}

const userGetByEmail = `-- name: UserGetByEmail :one
select id, email, password, first_name, last_name, created_at, updated_at, deleted_at from "user" 
where email = $1
  and deleted_at is null
`

func (q *Queries) UserGetByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, userGetByEmail, email)
	var i User
	err := row.Scan(
		&i.Id,
		&i.Email,
		&i.Password,
		&i.FirstName,
		&i.LastName,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	if err != nil {
		err = fmt.Errorf("query UserGetByEmail: %w", err)
	}
	return i, err
}
