// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package gensqlc

import (
	"context"
)

type Querier interface {
	UserCreate(ctx context.Context, arg UserCreateParams) (User, error)
	UserDeleteById(ctx context.Context, id int64) error
	UserGetByEmail(ctx context.Context, email string) (User, error)
}

var _ Querier = (*Queries)(nil)
