// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package gensqlc

import (
	"context"
	"fmt"

	"github.com/jackc/pgx/v5/pgconn"
)

const userDeleteById = `-- name: UserDeleteById :exec
update "user"
  set deleted_at = now()
where id = $1
`

func (q *Queries) UserDeleteById(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, userDeleteById, id)
	if err != nil {
		return fmt.Errorf("query UserDeleteById: %w", err)
	}
	return nil
}

const userGetByEmail = `-- name: UserGetByEmail :one
select id, email, password, first_name, last_name, created_at, updated_at, deleted_at from "user" 
where email = $1
  and deleted_at is null
`

func (q *Queries) UserGetByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, userGetByEmail, email)
	var i User
	err := row.Scan(
		&i.Id,
		&i.Email,
		&i.Password,
		&i.FirstName,
		&i.LastName,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	if err != nil {
		err = fmt.Errorf("query UserGetByEmail: %w", err)
	}
	return i, err
}

const userGetById = `-- name: UserGetById :one
select id, email, password, first_name, last_name, created_at, updated_at, deleted_at from "user" 
where id = $1
  and deleted_at is null
`

func (q *Queries) UserGetById(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, userGetById, id)
	var i User
	err := row.Scan(
		&i.Id,
		&i.Email,
		&i.Password,
		&i.FirstName,
		&i.LastName,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	if err != nil {
		err = fmt.Errorf("query UserGetById: %w", err)
	}
	return i, err
}

const userHardDeleteAll = `-- name: UserHardDeleteAll :execresult
delete from "user" returning id, email, password, first_name, last_name, created_at, updated_at, deleted_at
`

func (q *Queries) UserHardDeleteAll(ctx context.Context) (pgconn.CommandTag, error) {
	result, err := q.db.Exec(ctx, userHardDeleteAll)
	if err != nil {
		err = fmt.Errorf("query UserHardDeleteAll: %w", err)
	}
	return result, err
}

const userHardDeleteAllCnt = `-- name: UserHardDeleteAllCnt :execrows
delete from "user"
`

func (q *Queries) UserHardDeleteAllCnt(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, userHardDeleteAllCnt)
	if err != nil {
		return 0, fmt.Errorf("query UserHardDeleteAllCnt: %w", err)
	}
	return result.RowsAffected(), nil
}

const userHardDeleteByEmail = `-- name: UserHardDeleteByEmail :exec
delete from "user" where email = $1
`

func (q *Queries) UserHardDeleteByEmail(ctx context.Context, email string) error {
	_, err := q.db.Exec(ctx, userHardDeleteByEmail, email)
	if err != nil {
		return fmt.Errorf("query UserHardDeleteByEmail: %w", err)
	}
	return nil
}

const userInsert = `-- name: UserInsert :one
insert into "user" (
    email
  , password
  , first_name
  , last_name
) values (
    $1
  , $2
  , $3
  , $4
)
returning id, email, password, first_name, last_name, created_at, updated_at, deleted_at
`

type UserInsertParams struct {
	Email     string
	Password  []byte
	FirstName string
	LastName  string
}

func (q *Queries) UserInsert(ctx context.Context, arg UserInsertParams) (User, error) {
	row := q.db.QueryRow(ctx, userInsert,
		arg.Email,
		arg.Password,
		arg.FirstName,
		arg.LastName,
	)
	var i User
	err := row.Scan(
		&i.Id,
		&i.Email,
		&i.Password,
		&i.FirstName,
		&i.LastName,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	if err != nil {
		err = fmt.Errorf("query UserInsert: %w", err)
	}
	return i, err
}

type UserInsertManyCopyFromParams struct {
	Email     string
	Password  []byte
	FirstName string
	LastName  string
}

const userList = `-- name: UserList :many
select id, email, password, first_name, last_name, created_at, updated_at, deleted_at from "user"
`

func (q *Queries) UserList(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, userList)
	if err != nil {
		return nil, fmt.Errorf("query UserList: %w", err)
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.Id,
			&i.Email,
			&i.Password,
			&i.FirstName,
			&i.LastName,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, fmt.Errorf("query UserList: %w", err)
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("query UserList: %w", err)
	}
	return items, nil
}
