// Package pgxexec provides a unified interface for executing SQL queries
// and transactions using pgx. It is designed to work seamlessly
// with sqlc-generated code, allowing for easy integration.
package pgxexec

import (
	"context"
	"errors"
	"fmt"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgconn"
)

// DB defines a minimal common interface for pgx.Conn, pgxpool.Pool, and sqlc.DB
//
// It serves only for documentation purposes, because none of its
// methods are needed to implement the [Executor] interface.
type DB interface {
	Exec(context.Context, string, ...any) (pgconn.CommandTag, error)
	Query(context.Context, string, ...any) (pgx.Rows, error)
	QueryRow(context.Context, string, ...any) pgx.Row

	// Note: those methods are generated by sqlc only on specific annotations
	// thus  they are not part of the common interface.
	//
	// CopyFrom(ctx context.Context, tableName pgx.Identifier, columnNames []string, rowSrc pgx.CopyFromSource) (int64, error)
	// SendBatch(ctx context.Context, batch *pgx.Batch) pgx.BatchResults
}

// DBTX adds transaction capabilities to the DB interface.
type DBTX interface {
	DB
	Begin(ctx context.Context) (pgx.Tx, error)
	BeginTx(ctx context.Context, opts pgx.TxOptions) (pgx.Tx, error)
}

// QTx defines an interface for sqlc.Queries.
type QTx[Q any] interface {
	*Q
	WithTx(tx pgx.Tx) *Q
}

// Querier defines an interface for retrieving sqlc.Queries.
type Querier[Q any, Queries QTx[Q]] interface {
	Queries() Queries
}

// ExecutorDBTX defines an interface that is shared between
// Executor and Tx, allowing for transaction management and query execution.
type ExecutorDBTX[Q any, Queries QTx[Q]] interface {
	Querier[Q, Queries]
	Begin(ctx context.Context) (Tx[Q, Queries], error)
}

// Executor defines an interface for executing queries and managing transactions on database.
type Executor[Q any, Queries QTx[Q]] interface {
	ExecutorDBTX[Q, Queries]
	BeginTx(ctx context.Context, opts pgx.TxOptions) (Tx[Q, Queries], error)
	ExecInTx(ctx context.Context, fn func(tx Queries) error) error
	InTx(ctx context.Context, fn func(tx Tx[Q, Queries]) error) error
}

// Tx defines an interface for executing queries within a transaction.
type Tx[Q any, Queries QTx[Q]] interface {
	ExecutorDBTX[Q, Queries]
	ExecInTx(ctx context.Context, fn func(tx Queries) error) error
	InTx(ctx context.Context, fn func(tx Tx[Q, Queries]) error) error
	Commit(ctx context.Context) error
	Rollback(ctx context.Context) error
}

// NewExecutor creates a new Executor instance with the provided DBTX and Queries.
func NewExecutor[Q any, Queries QTx[Q]](
	dbtx DBTX,
	queries Queries,
) Executor[Q, Queries] {
	return executor[Q, Queries]{
		q:    queries,
		dbtx: dbtx,
	}
}

type TxExecutor[Q QTx[Q]] = Tx[Q, Q]

// executor implements the [Executor] interface, providing methods to execute queries
// and manage transactions using a pgx.Conn or pgxpool.Pool.
type executor[Q any, Queries QTx[Q]] struct {
	q    Queries
	dbtx DBTX
}

// Queries returns the sqlc.Queries instance associated with the executor.
func (e executor[Q, Queries]) Queries() Queries {
	return e.q
}

// Begin starts a new transaction using the underlying DBTX interface.
// see [pgx.Conn.Begin] or [pgxpool.Pool.Begin] for more details.
func (e executor[Q, Queries]) Begin(ctx context.Context) (Tx[Q, Queries], error) {
	tx, err := e.dbtx.Begin(ctx)
	if err != nil {
		return nil, fmt.Errorf("pgxexec begin: %w", err)
	}

	return newExecutorTx(tx, e.q), nil
}

// BeginTx starts a new transaction with the specified options using
// the underlying [DBTX] interface.
//
// see [pgx.TxOptions] for more details on transaction options.
func (e executor[Q, Queries]) BeginTx(
	ctx context.Context,
	opts pgx.TxOptions,
) (Tx[Q, Queries], error) {
	tx, err := e.dbtx.BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("pgxexec begin tx: %w", err)
	}

	return newExecutorTx(tx, e.q), nil
}

// InTx starts a new transaction with the specified options using
// the underlying [DBTX] interface.
func (e executor[Q, Queries]) ExecInTx(
	ctx context.Context,
	fn func(tx Queries) error,
) (err error) {
	tx, err := e.dbtx.Begin(ctx)
	if err != nil {
		return err
	}

	defer func() {
		if err != nil {
			err1 := tx.Rollback(ctx)
			if err1 != nil {
				err = errors.Join(err, err1)
			}
		}
	}()

	txq := newExecutorTx(tx, e.q)
	if err := fn(txq.Queries()); err != nil {
		return err
	}

	return tx.Commit(ctx)
}

// InTx starts a new transaction with the specified options using
// the underlying [DBTX] interface.
func (e executor[Q, Queries]) InTx(
	ctx context.Context,
	fn func(tx Tx[Q, Queries]) error,
) (err error) {
	tx, err := e.dbtx.Begin(ctx)
	if err != nil {
		return err
	}

	defer func() {
		if err != nil {
			err1 := tx.Rollback(ctx)
			if err1 != nil {
				err = errors.Join(err, err1)
			}
		}
	}()

	txq := newExecutorTx(tx, e.q)
	if err := fn(txq); err != nil {
		return err
	}

	return tx.Commit(ctx)
}

// executorTx implements the [Tx] interface, providing methods to execute queries.
type executorTx[Q any, Queries QTx[Q]] struct {
	q  Queries
	tx pgx.Tx
}

// newExecutorTx creates a new executorTx instance with
// the provided transaction and queries.
func newExecutorTx[Q any, Queries QTx[Q]](
	tx pgx.Tx,
	queries Queries,
) executorTx[Q, Queries] {
	return executorTx[Q, Queries]{
		q:  queries.WithTx(tx),
		tx: tx,
	}
}

// Queries returns the sqlc.Queries instance associated
// with the transaction executor.
func (e executorTx[Q, Queries]) Queries() Queries {
	return e.q
}

// Begin starts a pseudo nested transaction.
// see [pgx.Tx.Begin] for more details.
func (e executorTx[Q, Queries]) Begin(ctx context.Context) (Tx[Q, Queries], error) {
	tx, err := e.tx.Begin(ctx)
	if err != nil {
		return nil, fmt.Errorf("pgxexec tx begin: %w", err)
	}

	return newExecutorTx(tx, e.q), nil
}

// Commit the current transaction.
// see [pgx.Tx.Commit] for more details.
func (e executorTx[Q, Queries]) Commit(ctx context.Context) error {
	if err := e.tx.Commit(ctx); err != nil {
		return fmt.Errorf("pgxexec tx commit: %w", err)
	}
	return nil
}

// Rollback the current transaction.
// see [pgx.Tx.Rollback] for more details.
func (e executorTx[Q, Queries]) Rollback(ctx context.Context) error {
	if err := e.tx.Rollback(ctx); err != nil {
		return fmt.Errorf("pgxexec tx rollback: %w", err)
	}
	return nil
}

// InTx starts a new transaction with the specified options using
// the underlying [pgx.Tx] interface.
//
// see [pgx.Tx.Begin] for more details.
func (e executorTx[Q, Queries]) ExecInTx(ctx context.Context, fn func(tx Queries) error) (err error) {
	tx, err := e.tx.Begin(ctx)
	if err != nil {
		return err
	}

	defer func() {
		if err != nil {
			err1 := tx.Rollback(ctx)
			if err1 != nil {
				err = errors.Join(err, err1)
			}
		}
	}()

	txq := newExecutorTx(tx, e.q)
	if err := fn(txq.Queries()); err != nil {
		return err
	}

	return tx.Commit(ctx)
}

// WithTx starts a new transaction with the specified options using
// the underlying [pgx.Tx] interface.
//
// see [pgx.Tx.Begin] for more details.
func (e executorTx[Q, Queries]) InTx(ctx context.Context, fn func(tx Tx[Q, Queries]) error) (err error) {
	tx, err := e.tx.Begin(ctx)
	if err != nil {
		return err
	}

	defer func() {
		if err != nil {
			err1 := tx.Rollback(ctx)
			if err1 != nil {
				err = errors.Join(err, err1)
			}
		}
	}()

	txq := newExecutorTx(tx, e.q)
	if err := fn(txq); err != nil {
		return err
	}

	return tx.Commit(ctx)
}
