// Package pgxexec provides a unified interface for executing SQL queries
// and transactions using pgx. It is designed to work seamlessly
// with sqlc-generated code, allowing for easy integration.
package pgxexec

import (
	"context"
	"errors"
	"fmt"

	"github.com/jackc/pgx/v5"
)

// PgxTxBeginner represents a common database connection [pgx.Conn]/[pgxpool.Pool]
// interface that is capable of starting transactions.
type PgxTxBeginner interface {
	Begin(ctx context.Context) (pgx.Tx, error)
	BeginTx(ctx context.Context, opts pgx.TxOptions) (pgx.Tx, error)
}

// Queryable is the interface satisfied by sqlc.Queries pointer types
// (e.g. *gensqlc.Queries): a type that can rebind itself to a transaction.
type Queryable[Q any] interface {
	WithTx(tx pgx.Tx) Q
}

// Executor executes queries and manages transactions on a database.
//
// To avoid repeating the type parameter, define an alias for
// your queries type:
//
//	type Executor = pgxexec.Executor[*gensqlc.Queries]
type Executor[Q any] struct {
	q      Q
	withTx func(tx pgx.Tx) Q
	dbtx   PgxTxBeginner
}

// NewExecutor creates a new [Executor] instance for a [Queryable] queries type,
// such as sqlc-generated Queries.
func NewExecutor[Q Queryable[Q]](dbtx PgxTxBeginner, queries Q) Executor[Q] {
	return NewExecutorFn(dbtx, queries, queries.WithTx)
}

// NewExecutorFn creates a new [Executor] instance for any queries type,
// using withTx to rebind queries to a transaction. Use it when the queries
// type does not implement [Queryable], e.g. code not generated by sqlc:
//
//	exec := pgxexec.NewExecutorFn(pool, queries, func(tx pgx.Tx) *MyQueries {
//		return NewMyQueries(tx)
//	})
func NewExecutorFn[Q any](
	dbtx PgxTxBeginner,
	queries Q,
	withTx func(tx pgx.Tx) Q,
) Executor[Q] {
	return Executor[Q]{
		q:      queries,
		withTx: withTx,
		dbtx:   dbtx,
	}
}

// Queries returns the queries instance associated with the executor.
func (e Executor[Q]) Queries() Q {
	return e.q
}

// Begin starts a new transaction using the underlying [PgxTxBeginner] interface.
// see [pgx.Conn.Begin] or [pgxpool.Pool.Begin] for more details.
func (e Executor[Q]) Begin(ctx context.Context) (Tx[Q], error) {
	tx, err := e.dbtx.Begin(ctx)
	if err != nil {
		return Tx[Q]{}, fmt.Errorf("pgxexec begin: %w", err)
	}

	return newTx(tx, e.withTx), nil
}

// BeginTx starts a new transaction with the specified options using
// the underlying [PgxTxBeginner] interface.
//
// see [pgx.TxOptions] for more details on transaction options.
func (e Executor[Q]) BeginTx(ctx context.Context, opts pgx.TxOptions) (Tx[Q], error) {
	tx, err := e.dbtx.BeginTx(ctx, opts)
	if err != nil {
		return Tx[Q]{}, fmt.Errorf("pgxexec begin tx: %w", err)
	}

	return newTx(tx, e.withTx), nil
}

// ExecInTx runs fn inside a new transaction started via the underlying
// [PgxTxBeginner] interface, committing on success and rolling back on error.
func (e Executor[Q]) ExecInTx(ctx context.Context, fn func(tx Q) error) error {
	return queryInTx(e.Begin, ctx, fn)
}

// InTx runs fn inside a new transaction started via the underlying
// [PgxTxBeginner] interface, committing on success and rolling back on error.
func (e Executor[Q]) InTx(ctx context.Context, fn func(tx Tx[Q]) error) error {
	return execInTx(e.Begin, ctx, fn)
}

// Tx executes queries within a transaction.
//
// To avoid repeating the type parameter, define an alias for
// your queries type:
//
//	type TxQueries = pgxexec.Tx[*gensqlc.Queries]
type Tx[Q any] struct {
	q      Q
	withTx func(tx pgx.Tx) Q
	tx     pgx.Tx
}

// newTx creates a new [Tx] instance bound to the provided transaction.
func newTx[Q any](tx pgx.Tx, withTx func(tx pgx.Tx) Q) Tx[Q] {
	return Tx[Q]{
		q:      withTx(tx),
		withTx: withTx,
		tx:     tx,
	}
}

// Queries returns the queries instance associated
// with the transaction.
func (e Tx[Q]) Queries() Q {
	return e.q
}

// Begin starts a pseudo nested transaction.
// see [pgx.Tx.Begin] for more details.
func (e Tx[Q]) Begin(ctx context.Context) (Tx[Q], error) {
	tx, err := e.tx.Begin(ctx)
	if err != nil {
		return Tx[Q]{}, fmt.Errorf("pgxexec tx begin: %w", err)
	}

	return newTx(tx, e.withTx), nil
}

// Commit the current transaction.
// see [pgx.Tx.Commit] for more details.
func (e Tx[Q]) Commit(ctx context.Context) error {
	if err := e.tx.Commit(ctx); err != nil {
		return fmt.Errorf("pgxexec tx commit: %w", err)
	}
	return nil
}

// Rollback the current transaction.
// see [pgx.Tx.Rollback] for more details.
func (e Tx[Q]) Rollback(ctx context.Context) error {
	if err := e.tx.Rollback(ctx); err != nil {
		return fmt.Errorf("pgxexec tx rollback: %w", err)
	}
	return nil
}

// ExecInTx runs fn inside a nested transaction started via the underlying
// [pgx.Tx] interface, committing on success and rolling back on error.
//
// see [pgx.Tx.Begin] for more details.
func (e Tx[Q]) ExecInTx(ctx context.Context, fn func(tx Q) error) error {
	return queryInTx(e.Begin, ctx, fn)
}

// InTx runs fn inside a nested transaction started via the underlying
// [pgx.Tx] interface, committing on success and rolling back on error.
//
// see [pgx.Tx.Begin] for more details.
func (e Tx[Q]) InTx(ctx context.Context, fn func(tx Tx[Q]) error) error {
	return execInTx(e.Begin, ctx, fn)
}

func queryInTx[Q any](
	begin func(ctx context.Context) (Tx[Q], error),
	ctx context.Context,
	fn func(tx Q) error,
) error {
	tx, err := begin(ctx)
	if err != nil {
		return err
	}
	return runInTx(ctx, tx, func() error { return fn(tx.Queries()) })
}

func execInTx[Q any](
	begin func(ctx context.Context) (Tx[Q], error),
	ctx context.Context,
	fn func(tx Tx[Q]) error,
) error {
	tx, err := begin(ctx)
	if err != nil {
		return err
	}
	return runInTx(ctx, tx, func() error { return fn(tx) })
}

// runInTx calls fn, committing tx on success and rolling it back on error.
// If the rollback itself fails, its error is joined with fn's error.
func runInTx[Q any](ctx context.Context, tx Tx[Q], fn func() error) (err error) {
	defer func() {
		if err != nil {
			if err1 := tx.Rollback(ctx); err1 != nil {
				err = errors.Join(err, err1)
			}
		}
	}()

	if err := fn(); err != nil {
		return err
	}
	return tx.Commit(ctx)
}
